version: '3'

services:
  db:
    image: bitnami/postgresql:latest
    container_name: tab-tracker-postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres123
      POSTGRESQL_DATABASE: tab-tracker

volumes:
  postgresql_data:
    driver: local

networks:
  my-network:
    external: true
